### PR TITLE
ensure failed activations report errors

### PR DESCRIPTION
**Pull request by danshultz**
I noticed that errors were not reported properly as there is an extra promise created and returned but not resolved nor rejected.

I removed the outer promise as the nested calls are a promise chain. I'm going to look into creating some tests around the code a bit later. If you want to pair together when I get ready to this, let me know and we can work to try and schedule something.

Thanks!

### CODE REVIEW

**Comment by Kerry350** [comment]
Hey, thanks! :) I had refactored some methods and, yep, did bork the promise chain. It was on my TODO list in the README (never enough hours in a day) so you've saved me a job. Great stuff :D  

R.e. tests, that would be awesome. I'm more than happy for you to lead the way on them as I'm still learning when it comes to writing high quality tests. I'd been thinking how best to mock the S3 SDK. LevelBossMike had this [mock client](https://github.com/LevelbossMike/ember-deploy-s3/blob/master/node_tests/helpers/mock-s3.js) but it mocks a different module. All things I'd like to get better at. Would be up for the pairing; I've followed you on Twitter, we can maybe sort something via DMs?

**Comment by LevelbossMike** [comment]
Testing S3 stuff ich actually pretty annoying and the only useful way I found was to test against the S3-lib one is using (which should be tested of course) because it does not make much sense to integration test the lib one is using again in the adapter tests. That was my reasoning with the mock-client. Is there a reason you can't use the same s3 library as ember-deploy-s3 is using (features missing for example)?

I am not that happy with the s3-lib I am using myself so maybe it's a good idea to change to the same library

**Comment by Kerry350** [comment]
Thanks for your comment @LevelbossMike, it does sound like 'awkward' territory. I always feel like I'm never hitting the right balance on mocking :( 

I chose the official SDK as the `uploadFile()` method in the library ember-deploy-s3 was using had this note "This works with files, not streams or buffers." and the `upload()` method was being passed a buffer. It was a snap decision so to speak, I'm not sure if there was a way around it, but having never had a problem with the SDK (yet) I just used that.

**Comment by danshultz** [comment]
Ah, yeah - I was going to look to see what @LevelbossMike with the s3 stuff. I figured would go down the path of mocking S3 and using dependency injection to allow testing the scenarios and outcomes. I hadn't looked too deeply into it last night (EST time) when I pushed the PR.

I'll look at both repos and get up to speed on the s3 options for node and look at what was used in each scenario. I'll DM you @Kerry350 and we can chat a little bit. I'm also on IRC fairly regularly if anyone is around there and would like to chat.

@LevelbossMike the ember-deploy project appears to be in better shape than a few of the other things people have written thus far. I'd love to understand where the divergence of ember-cli-deploy and ember-deploy. I've seen a few others things people have tossed out there and wasn't sure if you had any background.

**Comment by LevelbossMike** [comment]
@danshultz yes there will be an update on ember-deploy vs. ember-cli-deploy at next week's emberconf. As Aaron already pointed out in his repo. The future proof way today is to use ember-deploy.

**Pull request merged**
