### PR TITLE
Add `prefix` config option

### PR DESCRIPTION
**Pull request by victorblasco**
What do you think @Kerry350 ? If you agree I will add tests :) Nice library!

### CODE REVIEW

**Comment by Kerry350** [comment]
Thanks :) I've just given this a whirl, I like it, should be useful to those grouping multiple apps in one bucket. I'll merge it now, and if you'd like to add tests in that'd be ace :+1:

**Comment by victorblasco** [comment]
Hmm these changes (with #14) broke the "activate revision" action (at least setting a `prefix` option) :( I needed this because we don't want to have 4 buckets (production and pre_production environments each of them with "index" and "assets" buckets), due to the limit of buckets (100 I think) in AWS. That way we can store all the stuff in one bucket, but it does not work with `putBucketWebsite()`.

I'll try to fix it, but in the meanwhile feel free to revert it!

**Comment by Kerry350** [comment]
@victorblasco Hmm, odd, I'd tried both out together and everything seemed fine. Unless I've misunderstood the desired behaviour. There's a small gif here where I've set a prefix of 'kittens' and activated a revision, which sets the index document correctly (using the new stuff from #14): https://cloudup.com/cMTLHusSJQM

As `activate` used to just set the contents of `index.html` equal to the contents of the revision I'm not sure where the behaviour has changed. 

I may have totally missed how this is being used though (sorry!). My understanding was a bucket could only have one index document, so with a multi-app bucket there'd probably be a server of some sort requesting the indexes rather than using the static site mode?  But if someone wanted to use a prefix for something like A/B testing and prefixing some sort of group of features that would make use of the index document. 

But yep, happy to revert if this is actually broken.

**Comment by LevelbossMike** [comment]
Can confirm that master is currently broken.

**Comment by Kerry350** [comment]
This PR is now reverted. I'm not sure if #14 should be reverted too, as things seemed to be working as intended for me?

**Pull request merged**
